import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmMono.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
